In [ ]:
from bs4 import BeautifulSoup as bsoup
import requests

#BeautifulSoup 모듈
#   HTTP에서 html을 긁어오는 모듈

#requests 모듈:
#   HTTP에 접근하는 모듈

html = requests.get('https://www.mozilla.org/ko/products/vpn/#pricing')
html
#200이 출력되면 접근이 허용됐다는 의미다.

In [ ]:
html.text

'\n\n\n\n\n\n\n\n\n\n\n<!doctype html>\n\n<html class="windows no-js" lang="ko" dir="ltr" data-country-code="US" data-needs-consent="False" data-latest-firefox="155.0.1" data-esr-versions="140.15.0 153.2.0" data-gtm-container-id="GTM-MW3R8V"  data-stub-attribution-rate="1.0" data-sentry-dsn="https://c3ab8514873549d5b3785ebc7fb83c80@o1069899.ingest.sentry.io/6260331" >\n  <head>\n    <meta charset="utf-8">\n\n    \n\n\n\n<script data-cfasync="false" src="https://transcend-cdn.com/cm/d556c3a1-e57c-4bdf-a490-390a1aebf6dd/airgap.js"></script>\n\n\n    <!--[if !IE]><!-->\n    <script src="https://www.mozilla.org/media/js/site.a6a07233d547.js"></script>\n\n    \n\n    <!--<![endif]-->\n\n    <!--[if IE 9]>\n    <script src="https://www.mozilla.org/media/js/site-ie.419ec4b57d17.js"></script>\n    <![endif]-->\n\n<!--\n\n\n             _.-~-.\n           7\'\'  Q..\\\n        _7         (_\n      _7  _/    _q.  /\n    _7 . ___  /VVvv-\'_                                            .\n   7/ / /~- \\_\\\\      \'-._     .-\'                      /       //\n  ./ ( /-~-/||\'=.__  \'::. \'-~\'\' {             ___   /  //     ./{\n V   V-~-~| ||   __\'\'_   \':::.   \'\'~-~.___.-\'\' _/  // / {_   /  {  /\n  VV/-~-~-|/ \\ .\'__\'. \'.    \'::                     _ _ _        \'\'.\n  / /~~~~||VVV/ /  \\ )  \\        _ __ ___   ___ ___(_) | | __ _   .::\'\n / (~-~-~\\\\.-\' /    \\\'   \\::::. | \'_ ` _ \\ / _ \\_  / | | |/ _` | :::\'\n/..\\    /..\\__/      \'     \'::: | | | | | | (_) / /| | | | (_| | ::\'\nvVVv    vVVv                 \': |_| |_| |_|\\___/___|_|_|_|\\__,_| \'\'\n\nHi there, nice to meet you!\n\nInterested in having a direct impact on hundreds of millions of users? Join\nMozilla, and become part of a global community that’s helping to build a\nbrighter future for the Web.\n\nVisit https://www.mozilla.org/careers to learn about our current job openings.\nVisit https://www.mozilla.org/contribute for more ways to get involved and\nhelp support Mozilla.\n-->\n\n    <meta name="viewport" content="width=device-width, initial-scale=1">\n    \n\n    \n    <title>Mozilla VPN: 모든 기기 보호</title>\n    <meta name="description" content="모든 기기와 앱 전체를 보호하려면 Mozilla VPN을 사용해 보세요. 57개 이상의 국가에 있는 서버로 어느 곳에서나 모든 곳으로 연결할 수 있습니다.">\n    <meta property="og:type" content="website">\n    <meta property="og:site_name" content="Mozilla">\n    <meta property="og:locale" content="ko">\n    <meta property="og:url" content="https://www.mozilla.org/ko/products/vpn/">\n    <meta property="og:image" content="https://www.mozilla.org/media/img/products/vpn/common/social-share.fd20884beaac.png">\n    <meta property="og:title" content="Mozilla VPN: 모든 기기 보호">\n    <meta property="og:description" content="모든 기기와 앱 전체를 보호하려면 Mozilla VPN을 사용해 보세요. 57개 이상의 국가에 있는 서버로 어느 곳에서나 모든 곳으로 연결할 수 있습니다.">\n    <meta property="fb:page_id" content="262134952380">\n    <meta name="twitter:card" content="summary">\n    <meta name="twitter:site" content="@mozilla">\n    <meta name="twitter:domain" content="mozilla.org">\n    <meta name="twitter:app:name:googleplay" content="Firefox">\n    <meta name="twitter:app:id:googleplay" content="org.mozilla.firefox">\n    <meta name="twitter:app:name:iphone" content="Firefox">\n    <meta name="twitter:app:id:iphone" content="989804926">\n    <meta name="twitter:app:name:ipad" content="Firefox">\n    <meta name="twitter:app:id:ipad" content="989804926">\n    <link rel="apple-touch-icon" type="image/png" sizes="180x180" href="https://www.mozilla.org/media/img/favicons/vpn/favicon.0f364a6c97eb.png">\n    <link rel="icon" type="image/png" sizes="196x196" href="https://www.mozilla.org/media/img/favicons/vpn/favicon.0f364a6c97eb.png">\n    <link rel="shortcut icon" href="https://www.mozilla.org/media/img/favicons/vpn/favicon.d2f92064332e.ico">\n    <link rel="canonical" href="https://www.mozilla.org/ko/products/vpn/">\n    \n    <link rel="alternate" hreflang="ar" href="https://www.mozilla.org/ar/products/vpn/" title="عربي">\n        <link rel="alternate" hreflang="be" href="https://www.mozilla.org/be/products/vpn/" title="Беларуская">\n        <link rel="alternate" hreflang="bg" href="https://www.mozilla.org/bg/products/vpn/" title="Български">\n        <link rel="alternate" hreflang="bs" href="https://www.mozilla.org/bs/products/vpn/" title="Bosanski">\n        <link rel="alternate" hreflang="cs" href="https://www.mozilla.org/cs/products/vpn/" title="Čeština">\n        <link rel="alternate" hreflang="cy" href="https://www.mozilla.org/cy/products/vpn/" title="Cymraeg">\n        <link rel="alternate" hreflang="da" href="https://www.mozilla.org/da/products/vpn/" title="Dansk">\n        <link rel="alternate" hreflang="de" href="https://www.mozilla.org/de/products/vpn/" title="Deutsch">\n        <link rel="alternate" hreflang="el" href="https://www.mozilla.org/el/products/vpn/" title="Ελληνικά">\n        <link rel="alternate" hreflang="en-CA" href="https://www.mozilla.org/en-CA/products/vpn/" title="English (Canadian)">\n        <link rel="alternate" hreflang="en-GB" href="https://www.mozilla.org/en-GB/products/vpn/" title="English (British)">\n        <link rel="alternate" hreflang="en" href="https://www.mozilla.org/en-US/products/vpn/" title="English">\n        <link rel="alternate" hreflang="en-US" href="https://www.mozilla.org/en-US/products/vpn/" title="English (USA)">\n        <link rel="alternate" hreflang="es-AR" href="https://www.mozilla.org/es-AR/products/vpn/" title="Español (de Argentina)">\n        <link rel="alternate" hreflang="es-CL" href="https://www.mozilla.org/es-CL/products/vpn/" title="Español (de Chile)">\n        <link rel="alternate" hreflang="es" href="https://www.mozilla.org/es-ES/products/vpn/" title="Español">\n        <link rel="alternate" hreflang="es-ES" href="https://www.mozilla.org/es-ES/products/vpn/" title="Español (de España)">\n        <link rel="alternate" hreflang="es-MX" href="https://www.mozilla.org/es-MX/products/vpn/" title="Español (de México)">\n        <link rel="alternate" hreflang="fr" href="https://www.mozilla.org/fr/products/vpn/" title="Français">\n        <link rel="alternate" hreflang="fy" href="https://www.mozilla.org/fy-NL/products/vpn/" title="Frysk">\n        <link rel="alternate" hreflang="fy-NL" href="https://www.mozilla.org/fy-NL/products/vpn/" title="Frysk">\n        <link rel="alternate" hreflang="gn" href="https://www.mozilla.org/gn/products/vpn/" title="Avañe\'ẽ">\n        <link rel="alternate" hreflang="hi" href="https://www.mozilla.org/hi-IN/products/vpn/" title="हिन्दी">\n        <link rel="alternate" hreflang="hi-IN" href="https://www.mozilla.org/hi-IN/products/vpn/" title="हिन्दी (भारत)">\n        <link rel="alternate" hreflang="hr" href="https://www.mozilla.org/hr/products/vpn/" title="Hrvatski">\n        <link rel="alternate" hreflang="hu" href="https://www.mozilla.org/hu/products/vpn/" title="magyar">\n        <link rel="alternate" hreflang="ia" href="https://www.mozilla.org/ia/products/vpn/" title="Interlingua">\n        <link rel="alternate" hreflang="id" href="https://www.mozilla.org/id/products/vpn/" title="Bahasa Indonesia">\n        <link rel="alternate" hreflang="it" href="https://www.mozilla.org/it/products/vpn/" title="Italiano">\n        <link rel="alternate" hreflang="ja" href="https://www.mozilla.org/ja/products/vpn/" title="日本語">\n        <link rel="alternate" hreflang="ka" href="https://www.mozilla.org/ka/products/vpn/" title="ქართული">\n        <link rel="alternate" hreflang="kk" href="https://www.mozilla.org/kk/products/vpn/" title="Қазақ">\n        <link rel="alternate" hreflang="ko" href="https://www.mozilla.org/ko/products/vpn/" title="한국어">\n        <link rel="alternate" hreflang="ms" href="https://www.mozilla.org/ms/products/vpn/" title="Melayu">\n        <link rel="alternate" hreflang="nb-NO" href="https://www.mozilla.org/nb-NO/products/vpn/" title="Norsk bokmål">\n        <link rel="alternate" hreflang="nl" href="https://www.mozilla.org/nl/products/vpn/" title="Nederlands">\n        <link rel="alternate" hreflang="nn-NO" href="https://www.mozilla.org/nn-NO/products/vpn/" title="Norsk nynorsk">\n        <link rel="alternate" hreflang="pa" href="https://www.mozilla.org/pa-IN/products/vpn/" title="ਪੰਜਾਬੀ">\n        <link rel="alternate" hreflang="pa-IN" href="https://www.mozilla.org/pa-IN/products/vpn/" title="ਪੰਜਾਬੀ (ਭਾਰਤ)">\n        <link rel="alternate" hreflang="pl" href="https://www.mozilla.org/pl/products/vpn/" title="Polski">\n        <link rel="alternate" hreflang="pt" href="https://www.mozilla.org/pt-BR/products/vpn/" title="Português">\n        <link rel="alternate" hreflang="pt-BR" href="https://www.mozilla.org/pt-BR/products/vpn/" title="Português (do\xa0Brasil)">\n        <link rel="alternate" hreflang="pt-PT" href="https://www.mozilla.org/pt-PT/products/vpn/" title="Português (Europeu)">\n        <link rel="alternate" hreflang="rm" href="https://www.mozilla.org/rm/products/vpn/" title="rumantsch">\n        <link rel="alternate" hreflang="ro" href="https://www.mozilla.org/ro/products/vpn/" title="Română">\n        <link rel="alternate" hreflang="ru" href="https://www.mozilla.org/ru/products/vpn/" title="Русский">\n        <link rel="alternate" hreflang="sk" href="https://www.mozilla.org/sk/products/vpn/" title="slovenčina">\n        <link rel="alternate" hreflang="sl" href="https://www.mozilla.org/sl/products/vpn/" title="Slovenščina">\n        <link rel="alternate" hreflang="sq" href="https://www.mozilla.org/sq/products/vpn/" title="Shqip">\n        <link rel="alternate" hreflang="sr" href="https://www.mozilla.org/sr/products/vpn/" title="Српски">\n        <link rel="alternate" hreflang="sv" href="https://www.mozilla.org/sv-SE/products/vpn/" title="Svenska">\n        <link rel="alternate" hreflang="sv-SE" href="https://www.mozilla.org/sv-SE/products/vpn/" title="Svenska">\n        <link rel="alternate" hreflang="tg" href="https://www.mozilla.org/tg/products/vpn/" title="Тоҷикӣ">\n        <link rel="alternate" hreflang="th" href="https://www.mozilla.org/th/products/vpn/" title="ไทย">\n        <link rel="alternate" hreflang="tr" href="https://www.mozilla.org/tr/products/vpn/" title="Türkçe">\n        <link rel="alternate" hreflang="uk" href="https://www.mozilla.org/uk/products/vpn/" title="Українська">\n        <link rel="alternate" hreflang="vi" href="https://www.mozilla.org/vi/products/vpn/" title="Tiếng Việt">\n        <link rel="alternate" hreflang="zh" href="https://www.mozilla.org/zh-CN/products/vpn/" title="中文">\n        <link rel="alternate" hreflang="zh-CN" href="https://www.mozilla.org/zh-CN/products/vpn/" title="中文 (简体)">\n        <link rel="alternate" hreflang="zh-TW" href="https://www.mozilla.org/zh-TW/products/vpn/" title="正體中文 (繁體)">\n        \n    \n    \n    <link href="https://mastodon.social/@mozilla" rel="me">\n\n    <!--[if lt IE 9]>\n      \n      <script src="https://www.mozilla.org/media/js/ie/libs/html5shiv.a94a0b700fa2.js"></script>\n    <![endif]-->\n\n    <!--[if IE]>\n      \n      \n        <link href="https://www.mozilla.org/media/css/common-old-ie.4d14f7a84a19.css" rel="stylesheet" type="text/css">\n      \n    <![endif]-->\n\n    <!--[if !IE]><!-->\n    \n    \n      <link href="https://www.mozilla.org/media/css/protocol-mozilla.54ea44c214ed.css" rel="stylesheet" type="text/css">\n      \n        <link href="https://www.mozilla.org/media/css/m24-navigation-and-footer.038277dadfff.css" rel="stylesheet" type="text/css">\n      \n      <link rel="stylesheet" href="https://www.mozilla.org/media/css/l10n/ko/intl.a6e7bf55b345.css">\n    \n\n    \n    \n  <link href="https://www.mozilla.org/media/css/protocol-split.b2c741eb3ef3.css" rel="stylesheet" type="text/css">\n  <link href="https://www.mozilla.org/media/css/protocol-picto.cfee40a3cd36.css" rel="stylesheet" type="text/css">\n  <link href="https://www.mozilla.org/media/css/mozilla-vpn-common-refresh.0deaf7afa17f.css" rel="stylesheet" type="text/css">\n  <link href="https://www.mozilla.org/media/css/mozilla-vpn-landing-refresh.4ab8beec8092.css" rel="stylesheet" type="text/css">\n\n    <!--<![endif]-->\n\n    \n      \n    \n\n    \n    \n      <!--[if IE 9]><!-->\n        \n\n<!--\nRead more about our custom configuration and use of Google Analytics here:\nhttps://bugzilla.mozilla.org/show_bug.cgi?id=1122305#c8\n-->\n\n<!-- Google Tag Manager -->\n<!-- Customized for Mozilla.org-->\n<!-- Region Container: NONE -->\n<!-- Rollup Container: System Filtered -->\n<!-- Site Container: NONE -->\n\n\n    <script src="https://www.mozilla.org/media/js/gtm-snippet.cc9550e6b401.js"></script>\n\n<!-- End Google Tag Manager -->\n      <!--<![endif]-->\n    \n  </head>\n\n  <body id="mozilla-vpn-landing" class="html-ltr mzp-t-mozilla" >\n    <div id="strings"\n      data-global-close="닫기"\n      data-global-next="다음"\n      data-global-previous="이전"\n      ></div>\n\n    \n      \n\n<aside class="moz-consent-banner" id="moz-consent-banner" role="region" aria-label="쿠키 배너" data-nosnippet="true" data-testid="consent-banner">\n  <div class="moz-consent-banner-content">\n    <h2 class="moz-consent-banner-heading">Mozilla 경험을 개선할 수 있도록 도와주세요</h2>\n    <div class="moz-consent-banner-copy">\n      <p>이 사이트가 작동하는 데 필요한 쿠키 외에도 탐색 요구를 더 잘 이해하고 경험을 개선하기 위해 추가 쿠키를 설정하려면 사용자의 허가가 필요합니다. 안심하세요. 우리는 사용자의 개인정보를 소중하게 생각합니다.</p>\n      <div class="moz-consent-banner-controls">\n        <button type="button" id="moz-consent-banner-button-accept" class="moz-consent-banner-button moz-consent-banner-button-accept" data-testid="consent-banner-accept-button">\n          모든 추가 쿠키 허용\n        </button>\n        <button type="button" id="moz-consent-banner-button-reject" class="moz-consent-banner-button moz-consent-banner-button-reject" data-testid="consent-banner-reject-button">\n          모든 추가 쿠키 거부\n        </button>\n        <a href="/ko/privacy/websites/cookie-settings/">\n          쿠키 설정\n        </a>\n      </div>\n    </div>\n  </div>\n</aside>\n    \n\n    \n  \n    \n\n\n  \n\n \n\n\n  \n\n\n\n\n\n  \n\n\n\n <nav class="m24-navigation-refresh enable-main-nav-sticky m24-mzp-is-sticky" aria-label="주요 항목">\n  <div class="m24-c-navigation-l-content">\n    <div class="m24-c-navigation-container">\n      <button class="m24-c-navigation-menu-button" type="button" aria-controls="m24-c-navigation-items" data-testid="m24-navigation-menu-button">메뉴</button>\n      <a class="m24-c-navigation-logo-link" href="/ko/" data-link-text="mozilla home icon" data-link-position="nav">\n        <img class="m24-c-navigation-logo-image" src="https://www.mozilla.org/media/img/logos/m24/lockup-black.f2ddba3f0724.svg" alt="Mozilla" width="101" height="24">\n      </a>\n      <div class="m24-c-navigation-items" id="m24-c-navigation-items" data-testid="m24-navigation-menu-items">\n        <div class="m24-c-navigation-menu">\n          <div class="m24-c-menu m24-mzp-is-basic">\n            <ul class="m24-c-menu-category-list">\n              \n\n\n\n<li class="m24-c-menu-category mzp-has-drop-down mzp-js-expandable">\n  <a class="m24-c-menu-title" href="/ko/products/" aria-haspopup="true" aria-controls="m24-c-menu-panel-products" data-testid="m24-navigation-link-products">제품</a>\n  <div class="m24-c-menu-panel" id="m24-c-menu-panel-products" data-testid="m24-navigation-panel-products">\n    <div class="m24-c-menu-panel-container" data-testid="m24-navigation-menu-products">\n      <button class="m24-c-menu-button-close" type="button" aria-controls="m24-c-menu-panel-products">제품 메뉴 닫기</button>\n      <div class="m24-c-menu-panel-content">\n        <ul class="m24-mzp-l-content">\n          <li>\n            <section class="m24-c-menu-item mzp-has-icon">\n              <a class="m24-c-menu-item-link" href="https://www.firefox.com?utm_source=www.mozilla.org&amp;utm_medium=referral&amp;utm_campaign=nav&amp;utm_content=products" data-link-text="Firefox browsers" data-link-position="topnav - products" data-testid="m24-navigation-menu-link-firefox">\n                <img loading="lazy" src="https://www.mozilla.org/media/protocol/img/logos/firefox/browser/logo.eb1324e44442.svg" class="m24-c-menu-item-icon" width="32" height="32" alt="">\n                <h2 class="m24-c-menu-item-title">Firefox 브라우저</h2>\n              </a>\n            </section>\n          </li>\n          <li>\n            <section class="m24-c-menu-item mzp-has-icon">\n              <a class="m24-c-menu-item-link" href="/ko/products/vpn/" data-link-text="Mozilla VPN" data-link-position="topnav - products" data-testid="m24-navigation-menu-link-products-vpn">\n                <img loading="lazy" src="https://www.mozilla.org/media/protocol/img/logos/mozilla/vpn/logo.c648f487bfb8.svg" class="m24-c-menu-item-icon" width="32" height="32" alt="">\n                <h2 class="m24-c-menu-item-title">Mozilla VPN</h2>\n              </a>\n            </section>\n          </li>\n          <li>\n            <section class="m24-c-menu-item mzp-has-icon">\n              \n                \n              \n              <a class="m24-c-menu-item-link" href="https://monitor.mozilla.org/?utm_source=www.mozilla.org&amp;utm_medium=referral&amp;utm_campaign=nav&amp;utm_content=products" data-link-text="Mozilla Monitor" data-link-position="topnav - products">\n                <img loading="lazy" src="https://www.mozilla.org/media/protocol/img/logos/firefox/monitor/logo.d97e5516f9e6.svg" class="m24-c-menu-item-icon" width="32" height="32" alt="">\n                <h2 class="m24-c-menu-item-title">Mozilla Monitor</h2>\n              </a>\n            </section>\n          </li>\n          <li>\n            <section class="m24-c-menu-item mzp-has-icon">\n              <a class="m24-c-menu-item-link" href="https://relay.firefox.com/?utm_source=www.mozilla.org&amp;utm_medium=referral&amp;utm_campaign=nav&amp;utm_content=products" data-link-text="Firefox Relay" data-link-position="topnav - products">\n                <img loading="lazy" src="https://www.mozilla.org/media/protocol/img/logos/firefox/relay/logo.d42a8b52e44c.svg" class="m24-c-menu-item-icon" width="32" height="32" alt="">\n                <h2 class="m24-c-menu-item-title">Firefox Relay</h2>\n              </a>\n            </section>\n          </li>\n          <li>\n            <section class="m24-c-menu-item mzp-has-icon">\n              <a class="m24-c-menu-item-link" href="https://developer.mozilla.org/plus?utm_source=www.mozilla.org&amp;utm_medium=referral&amp;utm_campaign=nav&amp;utm_content=products" data-link-text="MDN Plus" data-link-position="topnav - products">\n                <img loading="lazy" src="https://www.mozilla.org/media/img/logos/mdn/mdn-plus-logo.c615b46ca4ce.svg" class="m24-c-menu-item-icon" width="32" height="32" alt="">\n                <h2 class="m24-c-menu-item-title">MDN 플러스</h2>\n              </a>\n            </section>\n          </li>\n          <li>\n            <section class="m24-c-menu-item mzp-has-icon">\n              <a class="m24-c-menu-item-link" href="https://www.thunderbird.net/?utm_source=www.mozilla.org&amp;utm_medium=referral&amp;utm_campaign=nav&amp;utm_content=products" data-link-text="Thunderbird" data-link-position="topnav - products">\n                <img loading="lazy" src="https://www.mozilla.org/media/img/logos/thunderbird/logo-thunderbird.121e9c0fed45.svg" class="m24-c-menu-item-icon" width="32" height="32" alt="">\n                <h2 class="m24-c-menu-item-title">Thunderbird</h2>\n              </a>\n            </section>\n          </li>\n          <li>\n            <section class="m24-c-menu-item mzp-has-icon">\n              <a class="m24-c-menu-item-link" href="https://soloist.ai/?utm_source=www.mozilla.org&amp;utm_medium=referral&amp;utm_campaign=nav&amp;utm_content=products" data-link-text="Solo" data-link-position="topnav - products">\n                <img loading="lazy" src="https://www.mozilla.org/media/img/logos/solo/logo-solo.643cbd69b0d8.svg" class="m24-c-menu-item-icon" width="32" height="32" alt="">\n                <h2 class="m24-c-menu-item-t

In [ ]:
soup = bsoup(html.text, 'html.parser')
tag = soup.findAll('div', {'class' : 'mzp-c-split-body'})
#findAll(내용, 조건) - 리스트로 저장된다?
tag

/tmp/ipykernel_2213/3521383384.py:2: DeprecationWarning: Call to deprecated method findAll. (Replaced by find_all) -- Deprecated since version 4.0.0.
  tag = soup.findAll('div', {'class' : 'mzp-c-split-body'})

[<div class="mzp-c-split-body">
 <h1>안심할 수 있는 강력한 개인 정보 보호</h1>
 <p class="c-main-cta">
 <a class="mzp-c-button mzp-t-product mzp-t-xl" data-cta-position="primary" data-cta-text="Save on Mozilla VPN" data-testid="get-mozilla-vpn-hero-button" href="#pricing">
             Mozilla VPN*에서 50% 할인
           </a>
 <small>
             *연간 구독 사용 시
           </small>
 </p>
 </div>,
 <div class="mzp-c-split-body">
 <h2 class="u-title-lg">VPN이 무엇인가요?</h2>
 <p class="u-body-lg">
       가상 사설망은 인터넷 연결을 보호하여 사용자의 위치와 온라인 활동을 여러 기기에서 안전하게 보호합니다.
     </p>
 <p class="u-body-lg">
 <a href="/ko/products/vpn/features/">Mozilla VPN이 보호하는 모든 방법을 확인하세요.</a>
 </p>
 </div>,
 <div class="mzp-c-split-body">
 <h2 class="u-title-lg">신뢰할 수 있는 브랜드</h2>
 <p>Mozilla는 1998년부터 건강한 웹을 위해 싸워온 비영리 지원 인터넷 회사입니다.</p>
 </div>]

In [ ]:
for i in range(0, 3):
    print(tag[i].find('p').text)

            Mozilla VPN*에서 50% 할인


            *연간 구독 사용 시



      가상 사설망은 인터넷 연결을 보호하여 사용자의 위치와 온라인 활동을 여러 기기에서 안전하게 보호합니다.

Mozilla는 1998년부터 건강한 웹을 위해 싸워온 비영리 지원 인터넷 회사입니다.

In [ ]:
import seaborn as sns

titanic = sns.load_dataset('titanic')
titanic

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [ ]:
import google as ggl

ggl.colab.drive.mount('/content/gdrive/', force_remount=True)
path = "/content/gdrive/My Drive/Colab Notebooks/big_data/data_pre/titanic.csv"

titanic.to_csv(path)

Mounted at /content/gdrive/

In [ ]:
import pandas as pd
#pandas 모듈:
#   Panel Data의 약자
#   정형 데이터 전처리 모듈이다.
#   1차원 자료구조인 시리즈와
#   2차원 자료구조인 데이터프레임이 있다.
#   R 언어의 DataFrame을 본따 만들어졌다.
#   3차원 자료구조인 패널도 이따.

ttt = pd.read_csv(path)
ttt

,Unnamed: 0,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [ ]:
ttt.dtypes

Unnamed: 0       int64
survived         int64
pclass           int64
sex             object
age            float64
sibsp            int64
parch            int64
fare           float64
embarked        object
class           object
who             object
adult_male        bool
deck            object
embark_town     object
alive           object
alone             bool
dtype: object